In [7]:
from operator import index

import pandas as pd

#读取数据
df = pd.read_csv('resours/sales.csv',usecols=['订单号','产品类别','产品名称','销售数量','单价'])

#数据处理
df['销售金额'] = df['销售数量']*df['单价']
df

#写入数据
df.to_csv('resours/sales_01.csv',index = False)

df

            订单号  产品类别  产品名称  销售数量   单价  销售金额
0    6805677496  家居用品    枕头    10  199  1990
1    5857234132    食品    海苔     5   29   145
2    5888085059  电子产品  智能音箱     5  399  1995
3    6823473137    食品    面包     3   29    87
4    6801664364    食品    薯片     2   19    38
..          ...   ...   ...   ...  ...   ...
995  5887473055    图书    小说    10   49   490
996  5808511756    食品    坚果     2   79   158
997  5811169466    服装    围巾     4  129   516
998  6876456690    食品    果汁     7   39   273
999  6842608338    食品    蜂蜜     5   89   445

[1000 rows x 6 columns]

In [4]:
#数据查看-->head,tail,describe,info,shape,columns
df1 = pd.read_csv('resours/sales.csv',usecols=['订单号','产品类别','产品名称','销售数量','单价'])
df1.head(10)#查看前几行
df1.tail(10)#查看后几行
df1.describe()#显示数据统计信息
df1.info()#显示数据信息（列名，非空计数，数据类型等）
df1.shape#显示行数和列数
df1.columns#显示列名

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   订单号     1000 non-null   int64
 1   产品类别    1000 non-null   object
 2   产品名称    1000 non-null   object
 3   销售数量    1000 non-null   int64
 4   单价      1000 non-null   int64
dtypes: int64(3), object(2)
memory usage: 39.2+ KB

Index(['订单号', '产品类别', '产品名称', '销售数量', '单价'], dtype='object')

In [5]:
#数据选择
df2 = pd.read_csv('resours/sales.csv',usecols=['订单号','产品类别','产品名称','销售数量','单价'],index_col='订单号')
df2

#选择列
#1.1单/多列
df2[['产品类别','产品名称','单价']]

#2.选择行-iloc,loc
#2.1 iloc --->基于行号选择行，语法df.iloc[start:stop:step],不包括stop
df2.iloc[0:6]
#2.1 loc --->基于索引号选择行，语法df.loc[start:stop:step],包括stop
df2.loc[6805677496:5897064217:1]

            产品类别  产品名称  销售数量   单价
订单号
6805677496  家居用品    枕头    10  199
5857234132    食品    海苔     5   29
5888085059  电子产品  智能音箱     5  399
6823473137    食品    面包     3   29
6801664364    食品    薯片     2   19
5897064217    图书    字帖     4   29

In [6]:
df3 = pd.read_csv('resours/sales.csv')
df3

#配置项，展示所有的数据
#pd.set_option('display.max_rows', None)

#数据过滤
#1. 获取销售数量 >=10的订单数据
df3[df3['销售数量']>= 10]
#2. 获取产品类别为食品或图书的订单数据
df3[df3['产品类别'].isin(['食品','图书'])]
#3. 获取单价在100-200之间的订单数据,inclusive，可以觉得是否包含边界
df3[df3['单价'].between(100,200,inclusive="left")]
#4. 获取销售数量 >=8并且单价>=100的订单数据
df3[(df3['单价']>=100) & (df3['销售数量']>=8)]
#5. 获取产品类别为服装/食品，支付方式为支付宝/微信支付的订单数据
df3[(df3['产品类别'].isin(['服装','食品'])) & (df3['支付方式'].isin(['微信支付','支付宝']))]

            订单号 产品类别 产品名称  销售数量   单价 客户所在城市  支付方式        订单日期
4    6801664364   食品   薯片     2   19    NaN  微信支付  2025/06/02
10   5808071569   食品  矿泉水     9   29     重庆   支付宝  2025-06-04
16   5812573980   食品   坚果     2   79     南京  微信支付  2025-06-05
23   6867258691   服装   围巾     8  129     青岛  微信支付  2025-06-07
25   6837065480   服装   毛衣     3  399     深圳  微信支付  2025-06-07
..          ...  ...  ...   ...  ...    ...   ...         ...
993  6870828210   服装   内衣     8   89     广州  微信支付  2026-03-20
994  5860722276   服装   外套     6  599     广州  微信支付  2026-03-20
996  5808511756   食品   坚果     2   79     成都   支付宝  2026-03-20
997  5811169466   服装   围巾     4  129     南京   支付宝  2026-03-20
998  6876456690   食品   果汁     7   39     广州   支付宝  2026-03-20

[297 rows x 8 columns]