In [5]:
import pandas as pd

df = pd.read_csv('resours/sales.csv',nrows=20)

#排序
#2.1 根据 销售数量 倒序排序
df.sort_values('销售数量',ascending=False)
#2.2 根据 价格 升序排序
df.sort_values('单价',ascending=True)
#2.3 根据 价格 降序排序，价格一样，再根据 销售数量 升序排序
df.sort_values(['单价','销售数量'],ascending=[False,True])

           订单号  产品类别  产品名称  销售数量   单价 客户所在城市  支付方式        订单日期
2   5888085059  电子产品  智能音箱     5  399     福州  微信支付  2025-06-01
19  5852807025    服装    毛衣    10  399     重庆    现金  2025-06-05
8   5875402232  电子产品   路由器     9  299     福州   银行卡  2025-06-03
7   6898807429    服装    T恤     6  199     武汉   银行卡  2025-06-02
0   6805677496  家居用品    枕头    10  199     合肥   支付宝  2025-06-01
11  6890234923  家居用品  餐具套装    10  199     武汉    现金  2025-06-04
14  5804178086  电子产品  蓝牙耳机    10  199     重庆  微信支付  2025-06-04
9   5888085066    图书    字典     2   99     青岛  微信支付  2025-06-04
12  5891597362  电子产品    鼠标     3   89     合肥   银行卡  2025-06-04
16  5812573980    食品    坚果     2   79     南京  微信支付  2025-06-05
17  5835623429    图书    食谱     6   49     合肥   银行卡  2025-06-05
18  5852698441  家居用品    蜡烛     6   49     昆明    现金  2025-06-05
15  5878551159    图书   练习册     5   39     重庆    现金  2025-06-05
13  6880065056    图书   练习册     8   39     深圳   支付宝  2025-06-04
3   6823473137    食品    面包     3   29     北京   银行卡  2025-06-02
5   5897064217    图书    字帖     4   29     广州    现金  2025-06-02
1   5857234132    食品    海苔     5   29     天津    现金  2025-06-01
10  5808071569    食品   矿泉水     9   29     重庆   支付宝  2025-06-04
4   6801664364    食品    薯片     2   19    NaN  微信支付  2025/06/02
6   6857752388    服装    袜子     7  -29     郑州    现金  2025-06-02

In [6]:
df

           订单号  产品类别  产品名称  销售数量   单价 客户所在城市  支付方式        订单日期
0   6805677496  家居用品    枕头    10  199     合肥   支付宝  2025-06-01
1   5857234132    食品    海苔     5   29     天津    现金  2025-06-01
2   5888085059  电子产品  智能音箱     5  399     福州  微信支付  2025-06-01
3   6823473137    食品    面包     3   29     北京   银行卡  2025-06-02
4   6801664364    食品    薯片     2   19    NaN  微信支付  2025/06/02
5   5897064217    图书    字帖     4   29     广州    现金  2025-06-02
6   6857752388    服装    袜子     7  -29     郑州    现金  2025-06-02
7   6898807429    服装    T恤     6  199     武汉   银行卡  2025-06-02
8   5875402232  电子产品   路由器     9  299     福州   银行卡  2025-06-03
9   5888085066    图书    字典     2   99     青岛  微信支付  2025-06-04
10  5808071569    食品   矿泉水     9   29     重庆   支付宝  2025-06-04
11  6890234923  家居用品  餐具套装    10  199     武汉    现金  2025-06-04
12  5891597362  电子产品    鼠标     3   89     合肥   银行卡  2025-06-04
13  6880065056    图书   练习册     8   39     深圳   支付宝  2025-06-04
14  5804178086  电子产品  蓝牙耳机    10  199     重庆  微信支付  2025-06-04
15  5878551159    图书   练习册     5   39     重庆    现金  2025-06-05
16  5812573980    食品    坚果     2   79     南京  微信支付  2025-06-05
17  5835623429    图书    食谱     6   49     合肥   银行卡  2025-06-05
18  5852698441  家居用品    蜡烛     6   49     昆明    现金  2025-06-05
19  5852807025    服装    毛衣    10  399     重庆    现金  2025-06-05